"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {useAuthUser} from "../../../editor/auth";
import {createMapEditorSupabaseClient} from "../../../editor/supabase-client";

type Asset={id:string;name:string;slug:string|null;category:string|null;placement_category:string|null;role:string|null;asset_path:string|null;preview_path:string|null;grid_width:number|null;grid_height:number|null;tile_width:number|null;tile_height:number|null;perspective:string|null;palette_family:string|null;season_capable:boolean;autotile_capable:boolean;collision_capable:boolean;interactable:boolean;asset_status:string|null;asset_metadata:Record<string,unknown>|null;source_name:string|null;source_url:string|null;repository_url:string|null;source_version:string|null;licenses:string[];attribution_required:boolean;attribution_text:string|null;commercial_use_allowed:boolean;modification_allowed:boolean;redistribution_allowed:boolean};
type AssetFile={id:string;file_path:string;file_name:string;file_type:string;byte_size:number|null;width:number|null;height:number|null;sha256:string|null;verification_status:string;verification_method:string|null;is_primary:boolean;metadata:Record<string,unknown>|null};
type AssetPackage={id:string;package_name:string;package_key:string;evidence_status:string;package_root:string|null;evidence_source:string|null;relationship_type:string|null;evidence:string|null};
type PackageFile={id:string;file_path:string;file_name:string;file_type:string;byte_size:number|null;sha256:string|null;verification_status:string;verification_method:string|null;relation_type:string;metadata:Record<string,unknown>|null};

const WORLD_SOURCES=new Set(["[LPC] Terrains","[LPC] Overworld","LPC Revised 4-Seasons Exterior Tilesets"]);
function assetUrl(path:string|null,source:string|null){if(!path)return null;if(/^data:image\//i.test(path))return path;const repo=source&&WORLD_SOURCES.has(source)?"world":"library";if(/^https?:\/\/media\.githubusercontent\.com\/media\//i.test(path)){const i=path.indexOf("/raw/");const raw=i>=0?path.slice(i+5):path.split("/main/")[1]||"";return raw?"/api/assets/"+raw.split("/").map(encodeURIComponent).join("/")+"?repo=library":null;}if(/^https?:\/\//i.test(path))return path;return "/api/assets/"+path.split("/").map(encodeURIComponent).join("/")+"?repo="+repo;}
function Preview({asset}:{asset:Asset}){const embedded=/^data:image\//i.test(asset.preview_path||"")?asset.preview_path:null;const primary=embedded||assetUrl(asset.asset_path,asset.source_name);const fallback=embedded?assetUrl(asset.asset_path,asset.source_name):null;const[src,setSrc]=useState(primary);const[failed,setFailed]=useState(!primary);useEffect(()=>{setSrc(primary);setFailed(!primary)},[primary]);if(!src||failed)return <div style={{padding:50,textAlign:"center",opacity:.5}}>NO PREVIEW</div>;return <img src={src} alt={asset.name} style={{maxWidth:"100%",maxHeight:560,objectFit:"contain",display:"block",margin:"auto"}} onError={()=>{if(fallback&&src!==fallback){setSrc(fallback);return;}setFailed(true)}}/>}

export default function AssetDetailPage(){
 const router=useRouter();const params=useParams<{id:string}>();const{user,loading}=useAuthUser();const[asset,setAsset]=useState<Asset|null>(null);const[files,setFiles]=useState<AssetFile[]>([]);const[packages,setPackages]=useState<AssetPackage[]>([]);const[packageFiles,setPackageFiles]=useState<PackageFile[]>([]);const[failedGallery,setFailedGallery]=useState<string[]>([]);const[selectedImage,setSelectedImage]=useState<PackageFile|null>(null);const lightboxRef=useRef<HTMLDivElement|null>(null);const lightboxCloseRef=useRef<HTMLButtonElement|null>(null);const[fileFilter,setFileFilter]=useState("");const[busy,setBusy]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{if(loading||!user||!params?.id)return;let active=true;void(async()=>{const client=createMapEditorSupabaseClient();if(!client){setError("Supabase client belum tersedia.");setBusy(false);return;}const assetQuery=client.from("world_asset_browser_inventory_v1").select("*").eq("asset_status","approved").eq("id",params.id).maybeSingle();const filesQuery=client.from("asset_files").select("id,file_path,file_name,file_type,byte_size,width,height,sha256,verification_status,verification_method,is_primary,metadata").eq("asset_id",params.id).order("is_primary",{ascending:false}).order("file_name");const packageMembershipQuery=client.from("asset_package_assets").select("package_id,relationship_type,evidence").eq("asset_id",params.id);const[{data,error},{data:fileData,error:fileError},{data:membershipData,error:membershipError}]=await Promise.all([assetQuery,filesQuery,packageMembershipQuery]);if(!active)return;if(error){setError(error.message);setBusy(false);return;}if(fileError){setError(fileError.message);setBusy(false);return;}if(membershipError){setError(membershipError.message);setBusy(false);return;}const memberships=(membershipData??[])as Array<{package_id:string;relationship_type:string|null;evidence:string|null}>;let packageRows:AssetPackage[]=[];let packageFileRows:PackageFile[]=[];if(memberships.length){const ids=memberships.map(x=>x.package_id);const{data:packageData,error:packageError}=await client.from("asset_packages").select("id,package_name,package_key,evidence_status,package_root,evidence_source").in("id",ids);if(packageError){setError(packageError.message);setBusy(false);return;}packageRows=(packageData??[]).map(p=>{const m=memberships.find(x=>x.package_id===p.id);return{...p,relationship_type:m?.relationship_type??null,evidence:m?.evidence??null}})as AssetPackage[];const{data:packageFileData,error:packageFileError}=await client.from("asset_package_files").select("id,file_path,file_name,file_type,byte_size,sha256,verification_status,verification_method,relation_type,metadata").in("package_id",ids).order("file_type").order("file_name");if(packageFileError){setError(packageFileError.message);setBusy(false);return;}packageFileRows=(packageFileData??[])as PackageFile[];}setAsset((data??null)as Asset|null);setFiles((fileData??[])as AssetFile[]);setPackages(packageRows);setPackageFiles(packageFileRows);setBusy(false)})();return()=>{active=false}},[loading,user,params?.id]);
 const galleryFiles=useMemo(()=>packageFiles.filter(f=>/^(png|jpg|jpeg|webp|gif)$/i.test(f.file_type)&&!failedGallery.includes(f.id)),[packageFiles,failedGallery]);
 const filteredFiles=useMemo(()=>files.filter(f=>{const q=fileFilter.trim().toLowerCase();return !q||f.file_name.toLowerCase().includes(q)||f.file_path.toLowerCase().includes(q)||f.file_type.toLowerCase().includes(q)||f.verification_status.toLowerCase().includes(q)}),[files,fileFilter]);
 const verificationSummary=useMemo(()=>files.reduce((s,f)=>{const k=f.verification_status||"pending";s[k]=(s[k]||0)+1;return s},{} as Record<string,number>),[files]);
 const selectedIndex=selectedImage?galleryFiles.findIndex(f=>f.id===selectedImage.id):-1;
 const closeLightbox=()=>setSelectedImage(null);
 useEffect(()=>{if(!selectedImage)return;const previous=document.activeElement as HTMLElement|null;const focusTimer=window.setTimeout(()=>lightboxCloseRef.current?.focus(),0);const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();closeLightbox();return;}if(e.key==="ArrowRight"&&selectedIndex>=0&&selectedIndex<galleryFiles.length-1){e.preventDefault();setSelectedImage(galleryFiles[selectedIndex+1]);return;}if(e.key==="ArrowLeft"&&selectedIndex>0){e.preventDefault();setSelectedImage(galleryFiles[selectedIndex-1]);return;}if(e.key==="Tab"){const root=lightboxRef.current;if(!root)return;const focusable=Array.from(root.querySelectorAll<HTMLElement>('button:not([disabled]), a[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"]), [contenteditable="true"]'));if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};window.addEventListener("keydown",onKey);return()=>{window.clearTimeout(focusTimer);window.removeEventListener("keydown",onKey);previous?.focus?.()}},[selectedImage,selectedIndex,galleryFiles]);
 const note=useMemo(()=>{const v=asset?.asset_metadata?.description??asset?.asset_metadata?.evidence_text??asset?.asset_metadata?.provenance_status;return typeof v==="string"?v:"Tidak ada keterangan tambahan pada registry."},[asset]);
 if(loading)return <main style={{padding:32}}>Checking account…</main>;if(!user)return <main style={{padding:32}}><button type="button" onClick={()=>router.push("/")}>Back to Control Center</button></main>;if(busy)return <main style={{padding:32}}>Loading asset…</main>;if(!asset)return <main style={{padding:32}}><button type="button" onClick={()=>router.push("/asset-library")}>‹ Asset Library</button><h1>Asset tidak ditemukan</h1><p>{error||"Asset approved tidak ditemukan."}</p></main>;
 const box={border:"1px solid #26343a",borderRadius:14,padding:20,background:"#0c171d"};
 return <main style={{minHeight:"100vh",padding:"28px 32px",background:"#081016",color:"#e8ecec"}}>
  <button type="button" onClick={()=>router.push("/asset-library")} style={{background:"transparent",border:0,color:"#b8c0c2",fontSize:16,cursor:"pointer"}}>‹ Back to Asset Library</button>
  <header style={{margin:"24px 0 28px"}}><p style={{letterSpacing:4,opacity:.65,fontSize:12}}>VENDRITH ASSET SYSTEM · ASSET DETAIL</p><h1 style={{fontSize:"clamp(32px,5vw,54px)",margin:"8px 0"}}>{asset.name}</h1><strong style={{color:"#d7c47a"}}>{(asset.placement_category||"unassigned").toUpperCase()} · {asset.role||asset.category||"ASSET"}</strong></header>
  <section style={{display:"grid",gridTemplateColumns:"minmax(0,1.35fr) minmax(260px,.65fr)",gap:20}}><div style={box}><Preview asset={asset}/></div><div style={{display:"grid",gap:14}}><section style={box}><h2>PLACEMENT</h2><div style={{fontSize:28,color:"#d7c47a"}}>{(asset.placement_category||"unassigned").toUpperCase()}</div><p>Technical category: {asset.category||"—"}</p><p>Status: {asset.asset_status||"—"}</p></section><section style={box}><h2>SOURCE</h2><p>{asset.source_name||"—"}</p><p>Version: {asset.source_version||"—"}</p><p style={{wordBreak:"break-word"}}>{asset.asset_path||"—"}</p></section></div></section>
  <section style={{...box,marginTop:20}}><h2>PACKAGE STRUCTURE</h2><p style={{opacity:.7}}>Package/source relationships are shown only when the registry has an evidence-backed package binding. Package files are kept separately from the canonical asset manifest so shared package files are not duplicated into every asset record.</p>{packages.length===0?<p style={{opacity:.6}}>Belum ada package binding terverifikasi untuk asset ini.</p>:<div style={{display:"grid",gap:14}}>{packages.map(pkg=><div key={pkg.id} style={{borderTop:"1px solid #26343a",paddingTop:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><strong>{pkg.package_name}</strong><span style={{fontSize:12,opacity:.75}}>{pkg.evidence_status.toUpperCase()} · {pkg.relationship_type||"PACKAGE_MEMBER"}</span></div><div style={{opacity:.6,wordBreak:"break-word"}}>{pkg.package_root||"package root not recorded"}</div><div style={{marginTop:6,fontSize:13,opacity:.72}}>Package files: {packageFiles.length}{pkg.evidence_source?" · Evidence: "+pkg.evidence_source:""}</div>{pkg.evidence?<p style={{fontSize:13,opacity:.65}}>{pkg.evidence}</p>:null}</div>)}</div>}</section>
  <section style={{...box,marginTop:20}}><h2>PNG / IMAGE GALLERY</h2><p style={{opacity:.7}}>Preview gallery untuk binary image yang ditemukan dalam package evidence. Klik gambar untuk membuka tampilan besar; file package tetap dibedakan dari approved asset registry.</p>{galleryFiles.length===0?<p style={{opacity:.6}}>Belum ada image file yang dapat ditampilkan.</p>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:14}}>{galleryFiles.map(file=>{const src=assetUrl(file.file_path,asset.source_name);return <button key={file.id} type="button" onClick={()=>setSelectedImage(file)} style={{padding:0,textAlign:"left",border:"1px solid #26343a",borderRadius:12,overflow:"hidden",background:"#081016",color:"inherit",cursor:"zoom-in"}}><div style={{height:180,display:"flex",alignItems:"center",justifyContent:"center",padding:10,background:"#0a1318"}}>{src?<img src={src} alt={file.file_name} loading="lazy" style={{maxWidth:"100%",maxHeight:"100%",objectFit:"contain",display:"block"}} onError={e=>{e.currentTarget.style.display="none";setFailedGallery(v=>v.includes(file.id)?v:[...v,file.id])}}/>:<span style={{opacity:.5}}>NO URL</span>}</div><div style={{padding:10}}><strong style={{display:"block",fontSize:13,wordBreak:"break-word"}}>{file.file_name}</strong><span style={{fontSize:11,opacity:.65}}>{file.file_type.toUpperCase()} · {file.verification_status.toUpperCase()}</span><div style={{fontSize:11,opacity:.5,marginTop:4,wordBreak:"break-word"}}>{file.file_path}</div></div></button>})}</div>}</section>
  {selectedImage&&(()=>{const src=assetUrl(selectedImage.file_path,asset.source_name);return <div ref={lightboxRef} role="dialog" aria-modal="true" aria-label="Image preview" onMouseDown={e=>{if(e.target===e.currentTarget)closeLightbox()}} style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(0,0,0,.88)",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><button ref={lightboxCloseRef} type="button" onClick={closeLightbox} aria-label="Close" style={{position:"absolute",top:14,right:14,fontSize:28,width:44,height:44,border:"1px solid #566",borderRadius:999,background:"#0c171d",color:"#fff",cursor:"pointer"}}>×</button>{selectedIndex>0&&<button type="button" onClick={()=>setSelectedImage(galleryFiles[selectedIndex-1])} aria-label="Previous image" style={{position:"absolute",left:14,top:"50%",fontSize:30,width:48,height:48,border:"1px solid #566",borderRadius:999,background:"#0c171d",color:"#fff",cursor:"pointer"}}>‹</button>}{selectedIndex<galleryFiles.length-1&&<button type="button" onClick={()=>setSelectedImage(galleryFiles[selectedIndex+1])} aria-label="Next image" style={{position:"absolute",right:14,top:"50%",fontSize:30,width:48,height:48,border:"1px solid #566",borderRadius:999,background:"#0c171d",color:"#fff",cursor:"pointer"}}>›</button>}<div style={{maxWidth:"calc(100vw - 120px)",maxHeight:"calc(100vh - 60px)",width:"100%",display:"flex",flexDirection:"column",alignItems:"center",gap:10}}>{src?<img src={src} alt={selectedImage.file_name} style={{maxWidth:"100%",maxHeight:"70vh",objectFit:"contain"}}/>:null}<div style={{width:"100%",maxWidth:900,padding:"12px 16px",border:"1px solid #26343a",borderRadius:12,background:"#0c171d"}}><strong style={{display:"block",wordBreak:"break-word"}}>{selectedImage.file_name}</strong><span style={{fontSize:12,opacity:.7}}>{selectedIndex+1} / {galleryFiles.length} · {selectedImage.file_type.toUpperCase()} · {selectedImage.verification_status.toUpperCase()}</span><div style={{fontSize:11,opacity:.55,marginTop:5,wordBreak:"break-word"}}>{selectedImage.file_path}</div></div></div></div>})()}
  <section style={{...box,marginTop:20}}><h2>PACKAGE FILE INVENTORY</h2><p style={{opacity:.7}}>These are source/package files, including companion PNGs, TSX/TMX, previews, overlays, and documentation found in the audited package evidence. They are not automatically treated as independent approved assets.</p>{packageFiles.length===0?<p style={{opacity:.6}}>Belum ada package file inventory.</p>:<div style={{display:"grid",gap:10}}>{packageFiles.map(file=><div key={file.id} style={{borderTop:"1px solid #26343a",paddingTop:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><strong>{file.file_name}</strong><span style={{fontSize:12,opacity:.75}}>{file.file_type.toUpperCase()} · {file.verification_status.toUpperCase()}</span></div><div style={{opacity:.6,wordBreak:"break-word"}}>{file.file_path}</div><div style={{marginTop:6,fontSize:13,opacity:.72}}>{file.byte_size!=null?file.byte_size.toLocaleString()+" bytes":"size pending"}{file.sha256?" · SHA-256 "+file.sha256:""}{file.relation_type?" · "+file.relation_type:""}</div></div>)}</div>}</section>
  <section style={{...box,marginTop:20}}><h2>FILES IN THIS ASSET</h2><p style={{opacity:.7}}>Manifest canonical untuk asset ini. Status binary berasal dari audit manifest; file package tambahan tetap dipisahkan sampai hubungan source/package terverifikasi.</p><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0 16px"}}>{Object.entries(verificationSummary).map(([status,count])=><span key={status} style={{padding:"6px 10px",border:"1px solid #26343a",borderRadius:999,fontSize:12}}>{status.toUpperCase()} · {count}</span>)}<span style={{padding:"6px 10px",border:"1px solid #26343a",borderRadius:999,fontSize:12}}>TOTAL · {files.length}</span></div>{files.length>0&&<input value={fileFilter} onChange={e=>setFileFilter(e.target.value)} placeholder="Search filename, path, type, or verification status…" style={{width:"100%",boxSizing:"border-box",padding:"11px 12px",border:"1px solid #26343a",borderRadius:10,background:"#081016",color:"#e8ecec",marginBottom:14}}/>}{files.length===0?<p style={{opacity:.6}}>Belum ada file manifest.</p>:filteredFiles.length===0?<p style={{opacity:.6}}>Tidak ada file yang cocok dengan filter.</p>:<div style={{display:"grid",gap:10}}>{filteredFiles.map(file=><div key={file.id} style={{borderTop:"1px solid #26343a",paddingTop:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><strong>{file.file_name}</strong><span style={{fontSize:12,opacity:.75}}>{file.file_type.toUpperCase()} · {file.verification_status.toUpperCase()}{file.is_primary?" · PRIMARY":""}</span></div><div style={{opacity:.6,wordBreak:"break-word"}}>{file.file_path}</div><div style={{marginTop:6,fontSize:13,opacity:.72}}>{file.byte_size!=null?`${file.byte_size.toLocaleString()} bytes`:"size pending"}{file.width&&file.height?` · ${file.width}×${file.height}`:""}{file.sha256?` · SHA-256 ${file.sha256}`:""}</div></div>)}</div>}</section>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:14,marginTop:20}}><section style={box}><h2>METADATA</h2><p>{note}</p><p>Perspective: {asset.perspective||"—"}</p><p>Palette: {asset.palette_family||"—"}</p></section><section style={box}><h2>TECHNICAL</h2><p>Grid: {asset.grid_width??"—"} × {asset.grid_height??"—"}</p><p>Tile: {asset.tile_width??"—"} × {asset.tile_height??"—"}</p><p>Autotile: {asset.autotile_capable?"Yes":"No"} · Collision: {asset.collision_capable?"Yes":"No"} · Interactable: {asset.interactable?"Yes":"No"}</p></section><section style={box}><h2>LICENSE</h2><p>{asset.licenses?.length?asset.licenses.join(" · "):"Not recorded"}</p><p>Attribution: {asset.attribution_required?"Required":"Not required"}</p>{asset.attribution_text?<blockquote>{asset.attribution_text}</blockquote>:null}</section></section>
 </main>;
}