"use client";
import {useEffect,useMemo,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {useAuthUser} from "../../../editor/auth";
import {createMapEditorSupabaseClient} from "../../../editor/supabase-client";

type Asset={id:string;name:string;slug:string|null;category:string|null;placement_category:string|null;role:string|null;asset_path:string|null;preview_path:string|null;grid_width:number|null;grid_height:number|null;tile_width:number|null;tile_height:number|null;perspective:string|null;palette_family:string|null;season_capable:boolean;autotile_capable:boolean;collision_capable:boolean;interactable:boolean;asset_status:string|null;asset_metadata:Record<string,unknown>|null;source_name:string|null;source_url:string|null;repository_url:string|null;source_version:string|null;licenses:string[];attribution_required:boolean;attribution_text:string|null;commercial_use_allowed:boolean;modification_allowed:boolean;redistribution_allowed:boolean};

const WORLD_SOURCES=new Set(["[LPC] Terrains","[LPC] Overworld","LPC Revised 4-Seasons Exterior Tilesets"]);
function assetUrl(path:string|null,source:string|null){if(!path)return null;if(/^data:image\//i.test(path))return path;const repo=source&&WORLD_SOURCES.has(source)?"world":"library";if(/^https?:\/\/media\.githubusercontent\.com\/media\//i.test(path)){const i=path.indexOf("/raw/");const raw=i>=0?path.slice(i+5):path.split("/main/")[1]||"";return raw?"/api/assets/"+raw.split("/").map(encodeURIComponent).join("/")+"?repo=library":null;}if(/^https?:\/\//i.test(path))return path;return "/api/assets/"+path.split("/").map(encodeURIComponent).join("/")+"?repo="+repo;}
function Preview({asset}:{asset:Asset}){const embedded=/^data:image\//i.test(asset.preview_path||"")?asset.preview_path:null;const primary=embedded||assetUrl(asset.asset_path,asset.source_name);const fallback=embedded?assetUrl(asset.asset_path,asset.source_name):null;const[src,setSrc]=useState(primary);const[failed,setFailed]=useState(!primary);useEffect(()=>{setSrc(primary);setFailed(!primary)},[primary]);if(!src||failed)return <div style={{padding:50,textAlign:"center",opacity:.5}}>NO PREVIEW</div>;return <img src={src} alt={asset.name} style={{maxWidth:"100%",maxHeight:560,objectFit:"contain",display:"block",margin:"auto"}} onError={()=>{if(fallback&&src!==fallback){setSrc(fallback);return;}setFailed(true)}}/>}

export default function AssetDetailPage(){
 const router=useRouter();const params=useParams<{id:string}>();const{user,loading}=useAuthUser();const[asset,setAsset]=useState<Asset|null>(null);const[busy,setBusy]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{if(loading||!user||!params?.id)return;let active=true;void(async()=>{const client=createMapEditorSupabaseClient();if(!client){setError("Supabase client belum tersedia.");setBusy(false);return;}const{data,error}=await client.from("world_asset_browser_inventory_v1").select("*").eq("asset_status","approved").eq("id",params.id).maybeSingle();if(!active)return;if(error){setError(error.message);setBusy(false);return;}setAsset((data??null)as Asset|null);setBusy(false)})();return()=>{active=false}},[loading,user,params?.id]);
 const note=useMemo(()=>{const v=asset?.asset_metadata?.description??asset?.asset_metadata?.evidence_text??asset?.asset_metadata?.provenance_status;return typeof v==="string"?v:"Tidak ada keterangan tambahan pada registry."},[asset]);
 if(loading)return <main style={{padding:32}}>Checking account…</main>;if(!user)return <main style={{padding:32}}><button onClick={()=>router.push("/")}>Back to Control Center</button></main>;if(busy)return <main style={{padding:32}}>Loading asset…</main>;if(!asset)return <main style={{padding:32}}><button onClick={()=>router.push("/asset-library")}>‹ Asset Library</button><h1>Asset tidak ditemukan</h1><p>{error||"Asset approved tidak ditemukan."}</p></main>;
 const box={border:"1px solid #26343a",borderRadius:14,padding:20,background:"#0c171d"};
 return <main style={{minHeight:"100vh",padding:"28px 32px",background:"#081016",color:"#e8ecec"}}>
  <button onClick={()=>router.push("/asset-library")} style={{background:"transparent",border:0,color:"#b8c0c2",fontSize:16,cursor:"pointer"}}>‹ Back to Asset Library</button>
  <header style={{margin:"24px 0 28px"}}><p style={{letterSpacing:4,opacity:.65,fontSize:12}}>VENDRITH ASSET SYSTEM · ASSET DETAIL</p><h1 style={{fontSize:"clamp(32px,5vw,54px)",margin:"8px 0"}}>{asset.name}</h1><strong style={{color:"#d7c47a"}}>{(asset.placement_category||"unassigned").toUpperCase()} · {asset.role||asset.category||"ASSET"}</strong></header>
  <section style={{display:"grid",gridTemplateColumns:"minmax(0,1.35fr) minmax(260px,.65fr)",gap:20}}><div style={box}><Preview asset={asset}/></div><div style={{display:"grid",gap:14}}><section style={box}><h2>PLACEMENT</h2><div style={{fontSize:28,color:"#d7c47a"}}>{(asset.placement_category||"unassigned").toUpperCase()}</div><p>Technical category: {asset.category||"—"}</p><p>Status: {asset.asset_status||"—"}</p></section><section style={box}><h2>SOURCE</h2><p>{asset.source_name||"—"}</p><p>Version: {asset.source_version||"—"}</p><p style={{wordBreak:"break-word"}}>{asset.asset_path||"—"}</p></section></div></section>
  <section style={{...box,marginTop:20}}><h2>FILES IN THIS ASSET</h2><p style={{opacity:.7}}>Manifest audit berikutnya akan memetakan seluruh PNG/TMX/JSON yang benar-benar menjadi bagian package ini. Untuk sekarang registry menampilkan file canonical berikut.</p><div style={{borderTop:"1px solid #26343a",paddingTop:16}}><strong>{asset.asset_path?.split("/").pop()||asset.name}</strong><div style={{opacity:.6,wordBreak:"break-word"}}>{asset.asset_path||"—"}</div></div></section>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:14,marginTop:20}}><section style={box}><h2>METADATA</h2><p>{note}</p><p>Perspective: {asset.perspective||"—"}</p><p>Palette: {asset.palette_family||"—"}</p></section><section style={box}><h2>TECHNICAL</h2><p>Grid: {asset.grid_width??"—"} × {asset.grid_height??"—"}</p><p>Tile: {asset.tile_width??"—"} × {asset.tile_height??"—"}</p><p>Autotile: {asset.autotile_capable?"Yes":"No"} · Collision: {asset.collision_capable?"Yes":"No"} · Interactable: {asset.interactable?"Yes":"No"}</p></section><section style={box}><h2>LICENSE</h2><p>{asset.licenses?.length?asset.licenses.join(" · "):"Not recorded"}</p><p>Attribution: {asset.attribution_required?"Required":"Not required"}</p>{asset.attribution_text?<blockquote>{asset.attribution_text}</blockquote>:null}</section></section>
 </main>;
}