"use client";
import { useMemo, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { MapDocument, MapType } from '../editor/map-document';
import { buildMapTree, canCreateChildMap, createChildMap, getMapPath } from '../editor/map-manager';
import { createMap } from '../editor/map-document';
import { buildPlayableHierarchy, createInteriorFromExterior } from '../editor/playable-hierarchy';

type Props={maps:MapDocument[];activeMapId:string;onMapsChange:(maps:MapDocument[])=>void;onOpen:(id:string)=>void;client:SupabaseClient;onStatus?:(status:string)=>void};
const icon=(type:MapType,space?:string)=>type==='world'?'🌍':type==='region'?'🗺️':space==='interior'?'🏠':'🌳';
const errorMessage=(e:any)=>e?.message||e?.error_description||e?.details||e?.hint||String(e||'unknown error');
export function MapBrowser({maps,activeMapId,onMapsChange,onOpen,client,onStatus}:Props){const[collapsed,setCollapsed]=useState<Set<string>>(new Set());const[busy,setBusy]=useState(false);const active=maps.find(m=>m.id===activeMapId)??maps[0];const tree=useMemo(()=>buildMapTree(maps),[maps]);const playable=active?.mapType==='playable'?buildPlayableHierarchy(maps,active.id):null;const create=async()=>{if(!active||busy)return;const childType:MapType=active.mapType==='world'?'region':active.mapType==='region'?'playable':'playable';if(!canCreateChildMap(active,childType))return;setBusy(true);onStatus?.('Creating '+childType+' identity…');try{const rpc=await client.rpc('map_editor_create_child_v1',{p_parent_editor_map_id:active.id,p_map_type:childType,p_legacy_map_id:null});if(rpc.error)throw rpc.error;const result=Array.isArray(rpc.data)?rpc.data[0]:rpc.data;if(!result?.editor_map_id)throw new Error('EDITOR_CHILD_CREATE_FAILED');const base=createMap(childType,active.id,'exterior');const child=createChildMap(active,{...base,id:result.editor_map_id,name:'New '+(childType==='playable'?'Playable ':'')+'Exterior'});onMapsChange([...maps,child]);onStatus?.('Created '+childType+' identity · unsaved document');onOpen(child.id);}catch(e){onStatus?.('Create '+childType+' failed: '+errorMessage(e));}finally{setBusy(false);}};
const createInterior=async()=>{if(!active||active.mapType!=='playable'||active.playableSpace==='interior'||busy)return;setBusy(true);onStatus?.('Creating interior identity…');try{const rpc=await client.rpc('map_editor_create_interior_v1',{p_playable_editor_map_id:active.id,p_legacy_map_id:null,p_building_id:null});if(rpc.error)throw rpc.error;const result=Array.isArray(rpc.data)?rpc.data[0]:rpc.data;if(!result?.editor_map_id)throw new Error('EDITOR_INTERIOR_CREATE_FAILED');const base=createMap('playable',active.parentMapId,'interior',active.id);const child=createInteriorFromExterior(active,{...base,id:result.editor_map_id,name:active.name+' Interior'});onMapsChange([...maps,child]);onStatus?.('Created interior identity · unsaved document');onOpen(child.id);}catch(e){onStatus?.('Create interior failed: '+errorMessage(e));}finally{setBusy(false);}};const toggle=(id:string)=>setCollapsed(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n});const render=(nodes:any[],depth=0)=><>{nodes.map(node=><div key={node.id}><div style={{paddingLeft:depth*14,display:'flex',gap:4,alignItems:'center'}}><button disabled={busy} onClick={()=>node.children.length&&toggle(node.id)}>{node.children.length?(collapsed.has(node.id)?'▸':'▾'):'·'}</button><button disabled={busy} onClick={()=>onOpen(node.id)} aria-current={node.id===activeMapId?'page':undefined}>{icon(node.mapType,node.playableSpace)} {node.name}</button></div>{!collapsed.has(node.id)&&render(node.children,depth+1)}{node.mapType==='playable'&&node.playableSpace!=='interior'&&playableFor(node.id)}</div>)}</>;const playableFor=(id:string)=><>{(buildPlayableHierarchy(maps,id)?.interiors??[]).map(interior=><div key={interior.id} style={{paddingLeft:28}}><button disabled={busy} onClick={()=>onOpen(interior.id)} aria-current={interior.id===activeMapId?'page':undefined}>🏠 {interior.name}</button></div>)}</>;return <aside className="map-browser"><div className="section-title">Maps</div><div className="breadcrumb">{active&&getMapPath(active,maps).map((m,i)=><span key={m.id}>{i?' / ':''}{icon(m.mapType,m.playableSpace)} {m.name}</span>)}</div><div>{render(tree)}</div>{active?.mapType==='playable'&&active.playableSpace!=='interior'?<button disabled={busy} onClick={createInterior}>+ Create Interior</button>:<button disabled={busy||!active||active.mapType==='playable'} onClick={create}>+ {active?.mapType==='world'?'Create Region':'Create Playable Map'}</button>}</aside>}
