"use client";
import { useMemo, useState } from 'react';
import type { MapDocument, MapType } from '../editor/map-document';
import { buildMapTree, canCreateChildMap, createChildMap, getMapPath } from '../editor/map-manager';
import { createMap } from '../editor/map-document';
import { buildPlayableHierarchy, createInteriorFromExterior } from '../editor/playable-hierarchy';

type Props={maps:MapDocument[];activeMapId:string;onMapsChange:(maps:MapDocument[])=>void;onOpen:(id:string)=>void};
const icon=(type:MapType,space?:string)=>type==='world'?'🌍':type==='region'?'🗺️':space==='interior'?'🏠':'🌳';
export function MapBrowser({maps,activeMapId,onMapsChange,onOpen}:Props){const[collapsed,setCollapsed]=useState<Set<string>>(new Set());const active=maps.find(m=>m.id===activeMapId)??maps[0];const tree=useMemo(()=>buildMapTree(maps),[maps]);const playable=active?.mapType==='playable'?buildPlayableHierarchy(maps,active.id):null;const create=()=>{if(!active)return;const childType:MapType=active.mapType==='world'?'region':active.mapType==='region'?'playable':'playable';if(!canCreateChildMap(active,childType))return;const base=createMap(childType,active.id,'exterior');const child={...base,id:`${childType}-exterior-${Date.now()}`,name:`New ${childType==='playable'?'Playable ':''}Exterior`};onMapsChange([...maps,createChildMap(active,child)]);onOpen(child.id)};const createInterior=()=>{if(!active||active.mapType!=='playable'||active.playableSpace==='interior')return;const base=createMap('playable',active.parentMapId,'interior',active.id);const child=createInteriorFromExterior(active, {...base,id:`interior-${Date.now()}`,name:`${active.name} Interior`});onMapsChange([...maps,child]);onOpen(child.id)};const toggle=(id:string)=>setCollapsed(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n});const render=(nodes:any[],depth=0)=><>{nodes.map(node=><div key={node.id}><div style={{paddingLeft:depth*14,display:'flex',gap:4,alignItems:'center'}}><button onClick={()=>node.children.length&&toggle(node.id)}>{node.children.length?(collapsed.has(node.id)?'▸':'▾'):'·'}</button><button onClick={()=>onOpen(node.id)} aria-current={node.id===activeMapId?'page':undefined}>{icon(node.mapType,node.playableSpace)} {node.name}</button></div>{!collapsed.has(node.id)&&render(node.children,depth+1)}{node.mapType==='playable'&&node.playableSpace!=='interior'&&playableFor(node.id)}</div>)}</>;const playableFor=(id:string)=><>{(buildPlayableHierarchy(maps,id)?.interiors??[]).map(interior=><div key={interior.id} style={{paddingLeft:28}}><button onClick={()=>onOpen(interior.id)} aria-current={interior.id===activeMapId?'page':undefined}>🏠 {interior.name}</button></div>)}</>;return <aside className="map-browser"><div className="section-title">Maps</div><div className="breadcrumb">{active&&getMapPath(active,maps).map((m,i)=><span key={m.id}>{i?' / ':''}{icon(m.mapType,m.playableSpace)} {m.name}</span>)}</div><div>{render(tree)}</div>{active?.mapType==='playable'&&active.playableSpace!=='interior'?<button onClick={createInterior}>+ Create Interior</button>:<button onClick={create} disabled={!active||active.mapType==='playable'}>+ {active?.mapType==='world'?'Create Region':'Create Playable Map'}</button>}</aside>}
