"use client";
import { useMemo, useState } from 'react';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { WorldDocument, WorldType } from '../editor/map-document';
import { buildWorldTree, canCreateChildWorld, createChildWorld, getWorldPath } from '../editor/map-manager';
import { createWorld } from '../editor/map-document';
import { buildPlayableHierarchy, createInteriorFromExterior } from '../editor/playable-hierarchy';

type Props={worldDocuments:WorldDocument[];activeWorldId:string;onWorldChange:(worldDocuments:WorldDocument[])=>void;onOpenWorldDocument:(id:string,document?:WorldDocument)=>void;client?:SupabaseClient;onStatus?:(status:string)=>void};
const icon=(type:WorldType,space?:string)=>type==='world'?'🌍':type==='region'?'🗺️':space==='interior'?'🏠':'🌳';
const errorMessage=(e:any)=>e?.message||e?.error_description||e?.details||e?.hint||String(e||'unknown error');
export function WorldBrowser({worldDocuments,activeWorldId,onWorldChange,onOpenWorldDocument,client,onStatus}:Props){const[collapsed,setCollapsed]=useState<Set<string>>(new Set());const[busy,setBusy]=useState(false);const active=worldDocuments.find(m=>m.id===activeWorldId)??worldDocuments[0];const tree=useMemo(()=>buildWorldTree(worldDocuments),[worldDocuments]);const playable=active?.mapType==='playable'?buildPlayableHierarchy(worldDocuments,active.id):null;const create=async()=>{if(!active||busy)return;const childType:WorldType=active.mapType==='world'?'region':active.mapType==='region'?'playable':'playable';if(!canCreateChildWorld(active,childType))return;setBusy(true);onStatus?.('Creating '+childType+' identity…');try{if(!client)throw new Error('SUPABASE_UNAVAILABLE');let parentEditorWorldId=active.id;if(active.mapType==='world'){const bootstrap=await client.rpc('map_editor_bootstrap_world_identity_v1',{p_legacy_map_id:active.id});if(bootstrap.error)throw bootstrap.error;const bootstrapResult=Array.isArray(bootstrap.data)?bootstrap.data[0]:bootstrap.data;if(!bootstrapResult?.editor_map_id)throw new Error('EDITOR_WORLD_IDENTITY_BOOTSTRAP_FAILED');parentEditorWorldId=bootstrapResult.editor_map_id;}const rpc=await client.rpc('map_editor_create_child_v1',{p_parent_editor_map_id:parentEditorWorldId,p_map_type:childType,p_legacy_map_id:null});if(rpc.error)throw rpc.error;const result=Array.isArray(rpc.data)?rpc.data[0]:rpc.data;if(!result?.editor_map_id)throw new Error('EDITOR_CHILD_CREATE_FAILED');const base=createWorld(childType,active.id,'exterior');const child=createChildWorld(active,{...base,id:result.editor_map_id,name:'New '+(childType==='playable'?'Playable ':'')+'Exterior'});onWorldChange([...worldDocuments,child]);onStatus?.('Created '+childType+' identity · unsaved document');onOpenWorldDocument(child.id,child);}catch(e){onStatus?.('Create '+childType+' failed: '+errorMessage(e));}finally{setBusy(false);}};
const createInterior=async()=>{if(!active||active.mapType!=='playable'||active.playableSpace==='interior'||busy)return;setBusy(true);onStatus?.('Creating interior identity…');try{if(!client)throw new Error('SUPABASE_UNAVAILABLE');const rpc=await client.rpc('map_editor_create_interior_v1',{p_playable_editor_map_id:active.id,p_legacy_map_id:null,p_building_id:null});if(rpc.error)throw rpc.error;const result=Array.isArray(rpc.data)?rpc.data[0]:rpc.data;if(!result?.editor_map_id)throw new Error('EDITOR_INTERIOR_CREATE_FAILED');const base=createWorld('playable',active.parentWorldId,'interior',active.id);const child=createInteriorFromExterior(active,{...base,id:result.editor_map_id,name:active.name+' Interior'});onWorldChange([...worldDocuments,child]);onStatus?.('Created interior identity · unsaved document');onOpenWorldDocument(child.id);}catch(e){onStatus?.('Create interior failed: '+errorMessage(e));}finally{setBusy(false);}};const toggle=(id:string)=>setCollapsed(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n});const render=(nodes:any[],depth=0)=><>{nodes.map(node=><div key={node.id}><div style={{paddingLeft:depth*14,display:'flex',gap:4,alignItems:'center'}}><button disabled={busy} onClick={()=>node.children.length&&toggle(node.id)}>{node.children.length?(collapsed.has(node.id)?'▸':'▾'):'·'}</button><button disabled={busy} onClick={()=>onOpenWorldDocument(node.id,worldDocuments.find(m=>m.id===node.id))} aria-current={node.id===activeWorldId?'page':undefined}>{icon(node.mapType,node.playableSpace)} {node.name}</button></div>{!collapsed.has(node.id)&&render(node.children,depth+1)}{node.mapType==='playable'&&node.playableSpace!=='interior'&&playableFor(node.id)}</div>)}</>;const playableFor=(id:string)=><>{(buildPlayableHierarchy(worldDocuments,id)?.interiors??[]).map(interior=><div key={interior.id} style={{paddingLeft:28}}><button disabled={busy} onClick={()=>onOpenWorldDocument(interior.id,worldDocuments.find(m=>m.id===interior.id))} aria-current={interior.id===activeWorldId?'page':undefined}>🏠 {interior.name}</button></div>)}</>;return <aside className="world-browser"><div className="section-title">World</div><div className="breadcrumb">{active&&getWorldPath(active,worldDocuments).map((m,i)=><span key={m.id}>{i?' / ':''}{icon(m.mapType,m.playableSpace)} {m.name}</span>)}</div><div className="world-browser-tree">{render(tree)}</div>{active?.mapType==='playable'&&active.playableSpace!=='interior'?<button disabled={busy} onClick={createInterior}>+ Create Interior</button>:<button disabled={busy||!active||active.mapType==='playable'} onClick={create}>+ {active?.mapType==='world'?'Create Region':'Create Playable'}</button>}</aside>}
