import type { MapDocument } from './map-document';
import type { GridPoint } from './grid';
import { paintCell } from './map-state';

export type PaintShape='square'|'line'|'rectangle'|'flood';
const pointKey=(p:GridPoint)=>`${p.x}:${p.y}`;
export function pointsInSquare(center:GridPoint,size:number):GridPoint[]{const extent=Math.max(1,Math.floor(size)),before=Math.floor((extent-1)/2),after=extent-before-1,points:GridPoint[]=[];for(let y=center.y-before;y<=center.y+after;y++)for(let x=center.x-before;x<=center.x+after;x++)points.push({x,y});return points;}
const roundHalfDownRatio=(numerator:number,denominator:number)=>Math.floor((2*numerator+denominator-1)/(2*denominator));
export function pointsInLine(start:GridPoint,end:GridPoint):GridPoint[]{const dx=end.x-start.x,dy=end.y-start.y,absDx=Math.abs(dx),absDy=Math.abs(dy),points:GridPoint[]=[];if(absDx>=absDy){const step=dx<0?-1:1;for(let i=0;i<=absDx;i++){const x=start.x+i*step;const y=start.y+roundHalfDownRatio(dy*i,absDx||1);points.push({x,y});}}else{const step=dy<0?-1:1;for(let i=0;i<=absDy;i++){const y=start.y+i*step;const x=start.x+roundHalfDownRatio(dx*i,absDy||1);points.push({x,y});}}return points;}
export function pointsInRectangle(start:GridPoint,end:GridPoint):GridPoint[]{const minX=Math.min(start.x,end.x),maxX=Math.max(start.x,end.x),minY=Math.min(start.y,end.y),maxY=Math.max(start.y,end.y),points:GridPoint[]=[];for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)points.push({x,y});return points;}
export function pointsInFloodFill(document:MapDocument,layerId:string,start:GridPoint):GridPoint[]{if(start.x<0||start.y<0||start.x>=document.width||start.y>=document.height)return[];const layer=document.layers.find(item=>item.id===layerId);if(!layer)return[];const target=layer.cells[start.y*document.width+start.x]?.tileId??null,queue=[start],seen=new Set<string>([pointKey(start)]),result:GridPoint[]=[];while(queue.length){const point=queue.shift()!;result.push(point);for(const next of[{x:point.x+1,y:point.y},{x:point.x-1,y:point.y},{x:point.x,y:point.y+1},{x:point.x,y:point.y-1}]){if(next.x<0||next.y<0||next.x>=document.width||next.y>=document.height)continue;const key=pointKey(next);if(seen.has(key)||((layer.cells[next.y*document.width+next.x]?.tileId??null)!==target))continue;seen.add(key);queue.push(next);}}return result;}
export function pointsForPaintShape(document:MapDocument,layerId:string,shape:PaintShape,start:GridPoint,end=start,size=1):GridPoint[]{switch(shape){case'square':return pointsInSquare(end,size);case'line':return pointsInLine(start,end);case'rectangle':return pointsInRectangle(start,end);case'flood':return pointsInFloodFill(document,layerId,start);}}
export function applyPaint(document:MapDocument,layerId:string,points:GridPoint[],tileId:string|null):MapDocument{const unique=new Map<string,GridPoint>();for(const point of points)unique.set(pointKey(point),point);let next=document;for(const point of unique.values())next=paintCell(next,layerId,point,tileId);return next;}
